services:
  app:
    image: bloglist-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - 5173:80
    container_name: bloglist-frontend

  server:
    image: bloglist-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      MONGO_URL: mongodb+srv://admin:Rival844@phonebook.8t18iim.mongodb.net/?retryWrites=true&w=majority
    ports: 
      - 3000:3000
    container_name: bloglist-backend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server